<script type="text/javascript">
zray.registerExtensionLoaded('CodeIgniter', function(extensionData, requestData) {
//	jQuery('#codeigniter-installation-steps').remove();
//	jQuery('#codeigniter-extension-not-installed').css('display', 'block');
});

zray.registerDataHandler('CodeIgniter', 'installation', function(extensionData, requestData) {
    console.log(extensionData);
	if(extensionData[2] == false){
		jQuery('#codeigniter-current-version').text(extensionData[0]);
        jQuery('#codeigniter-supported-version').text(extensionData[1]);
        jQuery('#codeigniter-extension-not-installed').css('display', 'block');
        jQuery('#codeigniter-installation-steps').css('display', 'none');
    }
    else if(extensionData[3] == false){
        jQuery('#codeigniter-installation-steps').css('display', 'block');
    }
	else{
		jQuery('div[data-name="zrayExtension:CodeIgniter/installation"]').remove();
	}
});
	
</script>

<?php
if (!function_exists('image_base64_encode')) {
    function image_base64_encode($image)
    {
        $type = pathinfo($image, PATHINFO_EXTENSION);
        $data = file_get_contents($image);

        return 'data:image/' . $type . ';base64,' . base64_encode($data);
    }
}
?>
<style>
    #zend-dev-bar #codeigniter-extension-not-installed {
        height: 100px;
        background-image: url(<?php echo image_base64_encode(__DIR__ . '/../images/failure.png'); ?>);
        background-position: 28px 22px;
        padding-left: 74px;
        font-size: 18px;
        background-repeat: no-repeat;
        padding-top: 26px;
    }
    #zend-dev-bar #codeigniter-extension-not-installed h4{ font-size:12px }
</style>

<div id="codeigniter-installation-steps" style="padding: 10px;">

    <div style="font-size: 14px;">
        To complete the installation please follow the instructions below :
        <br/>
        <p>- locate the application/core folder in your CodeIgniter application,
 			create a new PHP file 'MY_Loader.php' and copy the following code in it from MY_Loader Class.</p>
        /!\ NOTE : If you are using HMVC third party copy the code from MX_Loader Class instead of MY_Loader Class :
    </div>
    <br/>
    <h2 style="font-weight:bold;font-size:14px">MY_Loader Class :</h2>
    <pre style="font-family: consolas, monospace;"><?php highlight_string(file_get_contents(__DIR__ . '/../Core/MY_Loader.php')); ?></pre>
    
    <h2 style="font-weight:bold;font-size:14px">MX_Loader Class :</h2>
    <pre style="font-family: consolas, monospace;"><?php highlight_string(file_get_contents(__DIR__ . '/../Core/MX_Loader.php')); ?></pre>
</div>

<div id="codeigniter-extension-not-installed" style="display: none;">
<h2>Installation failed : Unsupported version of CodeIgniter.</h2><br>
<h4>Current version : <span id="codeigniter-current-version"></span></h4>
<h4>Supported version : <span id="codeigniter-supported-version"></span></h4>
</div>